name: release

on:
  push:
    tags:
      - '*'

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t skaji/relocatable-perl -f build/Dockerfile .
      - run: bash build/github-actions.sh linux_amd64_create_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: linux-amd64
          path: linux-amd64
  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx build --platform linux/arm64 -t skaji/relocatable-perl -f build/Dockerfile --load .
      - run: bash build/github-actions.sh linux_arm64_create_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: linux-arm64
  linux-ppc64le:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx build --platform linux/ppc64le -t skaji/relocatable-perl -f build/Dockerfile .
      - run: bash build/github-actions.sh linux_ppc64le_create_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: linux-ppc64le
          path: linux-ppc64le
  linux-s390x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx build --platform linux/s390x -t skaji/relocatable-perl -f build/Dockerfile .
      - run: bash build/github-actions.sh linux_s390x_create_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: linux-s390x
          path: linux-s390x
  darwin-amd64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: |
          uname -a
          sw_vers
          system_profiler SPHardwareDataType
      - run: bash build/github-actions.sh mac_prepare_tools
      - run: bash build/github-actions.sh mac_build_perl
      - run: bash build/github-actions.sh mac_create_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: darwin-amd64
          path: darwin-amd64
  darwin-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: |
          uname -a
          sw_vers
          system_profiler SPHardwareDataType
      - run: bash build/github-actions.sh mac_prepare_tools
      - run: bash build/github-actions.sh mac_build_perl
      - run: bash build/github-actions.sh mac_create_artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: darwin-arm64
          path: darwin-arm64
  release:
    runs-on: ubuntu-latest
    needs:
      - linux-amd64
      - linux-arm64
      - linux-ppc64le
      - linux-s390x
      - darwin-amd64
      - darwin-arm64
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-amd64
          path: linux-amd64
      - uses: actions/download-artifact@v4
        with:
          name: linux-arm64
          path: linux-arm64
      - uses: actions/download-artifact@v4
        with:
          name: linux-ppc64le
          path: linux-ppc64le
      - uses: actions/download-artifact@v4
        with:
            name: linux-s390x
            path: linux-s390x
      - uses: actions/download-artifact@v4
        with:
          name: darwin-amd64
          path: darwin-amd64
      - uses: actions/download-artifact@v4
        with:
          name: darwin-arm64
          path: darwin-arm64
      - name: create release and upload release assets
        run: gh release create --repo ${{ github.repository }} ${{ github.ref }} linux-*/*.gz linux-*/*.xz darwin-*/*.gz darwin-*/*.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
